import os
import pandas as pd
import google.generativeai as genai

api_key = os.environ.get("GEMINI_API_KEY")
if api_key:
    genai.configure(api_key=api_key)
else:
    print("Warning: GEMINI_API_KEY is not set.")


def generate_analyst_report(
    ticker_name: str,
    ticker_code: str,
    latest_data_dict: list[dict],
    predictions_dict: list[dict],
) -> str:
    """Return an investment report generated by Gemini."""
    if not api_key or os.environ.get("PYTEST_CURRENT_TEST"):
        return "Gemini API key is not configured."

    latest_data_text = (
        pd.DataFrame(latest_data_dict).to_string(index=False)
        if latest_data_dict
        else "（テクニカル指標データなし）"
    )
    predictions_text = (
        pd.DataFrame(predictions_dict).to_string(index=False)
        if predictions_dict
        else "（モデル予測データなし）"
    )

    prompt = f"""
あなたは、機械学習モデルの出力を解釈し、具体的な投資戦略を立案することに特化した、
トップクラスのクオンツ・アナリストです。感情や主観を排し、与えられたデータのみに基
づいて、論理的な結論を導き出します。

これから、以下のデータに基づいて、**{ticker_name} ({ticker_code})** の投資判断レポート
を**指定のMarkdown形式**で作成してください。**指定されたフォーマット以外の余計な文
章は一切含めないでください。**

---
### **【入力データ】**

#### 最新のテクニカル指標
{latest_data_text}

#### 機械学習モデルによる予測
{predictions_text}
---

### **【アウトプット】**

```markdown
### 投資戦略サマリー：{ticker_name}

| 評価軸 | 分析結果と判断 |
|:---|:---|
| **短期トレンド (1-7日)** | （入力データに基づき、「強気」「中立」「弱気」のいずれかで評
価し、その根拠（例: 「1日後UP予測だが、期待リターンが低く限定的」など）を簡潔に記述） |
| **中期トレンド (28日)** | （入力データに基づき、「強気」「中立」「弱気」のいずれかで評
価し、その根拠（例: 「28日後はDOWN予測で、期待リターンも大きくマイナス」など）を簡潔
に記述） |
| **モデルの信頼性** | （上昇確率が50%に近いか、大きく偏っているかに基づき、「確信度
高」「確信度中」「確信度低」のいずれかで評価） |
| **総合評価** | （上記3点を統合した最終的な投資スタンスを「買い推奨」「様子見」
「売り推奨」で明確に記述） |

#### **具体的なアクションプラン**

*   **推奨アクション:** （「即時買い」「押し目買い」「戻り売り」「即時売り」など、具
体的な行動を推奨）
*   **ターゲット / ストップロス:** （期待リターンやテクニカル指標を参考に、具体的な目
標価格と損切り価格の目安を提示。判断が難しい場合は「N/A」と記述）
```
"""
    try:
        model = genai.GenerativeModel("gemini-1.5-flash")
        generation_config = genai.types.GenerationConfig(temperature=0.2)
        response = model.generate_content(
            prompt, generation_config=generation_config
        )
        return response.text
    except Exception as e:
        return f"Error generating report from Gemini: {e}"
