name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Create venv & install dependencies
        shell: bash
        run: |
          python3 -m venv .venv
          source .venv/bin/activate
          pip install --upgrade pip setuptools wheel
          pip install -r requirements.txt -r requirements-dev.txt
          # これで pandas と openpyxl も入り、Excelスクリプトが動くようになる
      - name: Run Tests
        shell: bash
        env:
          SECRET_KEY: "a-dummy-secret-key-for-testing"
          DEBUG: "True"
          DATABASE_URL: "sqlite:///:memory:"
        run: |
          # 仮想環境の pytest を直接実行
          source .venv/bin/activate
          pytest -q
      - name: Lint with flake8
        shell: bash
        run: |
          # 仮想環境以下を除外して lint
          .venv/bin/python -m flake8 . --exclude .venv
