 name: Django CI

 on:
   push:
     branches: [ "main" ]
   pull_request:
     branches: [ "main" ]

 jobs:
   build:
     runs-on: ubuntu-latest
     strategy:
       matrix:
         python-version: ["3.11"]

     steps:
     - uses: actions/checkout@v4

     - name: Set up Python ${{ matrix.python-version }}
       uses: actions/setup-python@v5
       with:
         python-version: ${{ matrix.python-version }}

-    - name: Install Dependencies
-      run: |
-        python -m venv .venv
-        . .venv/bin/activate
-        python -m pip install --upgrade pip
-        pip install -r requirements.txt
+    - name: Create venv & install dependencies
+      run: |
+        python -m venv .venv
+        # venv の python 経由で pip をアップグレードして必要なツールを追加
+        .venv/bin/python -m pip install --upgrade pip setuptools wheel
+        # 本番依存＋テスト依存をまとめてインストール
+        .venv/bin/python -m pip install \
+          -r requirements.txt \
+          -r requirements-dev.txt

-    - name: Run Tests
+    - name: Run Tests
       env:
         SECRET_KEY: "a-dummy-secret-key-for-testing"
         DEBUG: "True"
         DATABASE_URL: "sqlite:///:memory:"
-      run: |
-        . .venv/bin/activate
-        pytest -q
+      run: |
+        # venv の pytest を直接呼び出す
+        .venv/bin/python -m pytest -q

-    - name: Lint with flake8
-      run: |
-        . .venv/bin/activate
-        pip install flake8
-        flake8 .
+    - name: Lint with flake8
+      run: |
+        # flake8 は requirements-dev.txt に入れておけばここではインストール不要
+        .venv/bin/python -m flake8 .
