name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Create venv & install dependencies
        run: |
          python -m venv .venv
          # venv の python 経由で pip をアップグレードして必要なツールを追加
          .venv/bin/python -m pip install --upgrade pip setuptools wheel
          # 本番依存＋テスト依存をまとめてインストール
          .venv/bin/python -m pip install \
            -r requirements.txt \
            -r requirements-dev.txt

      - name: Run Tests
        env:
          SECRET_KEY: "a-dummy-secret-key-for-testing"
          DEBUG: "True"
          DATABASE_URL: "sqlite:///:memory:"
        run: |
          # venv の pytest を直接呼び出す
          .venv/bin/python -m pytest -q

      - name: Lint with flake8
        run: |
          # flake8 は requirements-dev.txt に含まれている想定なので、インストール不要
          .venv/bin/python -m flake8 .
