name: Railway Post Deploy

on:
  workflow_run:
    workflows: ["Deploy to Railway"]
    types:
      - completed

jobs:
  post-deploy-commands:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Railway CLI
        uses: railwayapp/cli@v2

      - name: Run Database Migrations
        run: railway run python manage.py migrate
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}

      - name: Populate Database from CSV
        run: railway run python scripts/update_tickers_from_csv.py
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
